#!/bin/sh

# This hacked up version works, at least on Linux, even for people who
# have spaces in the names of directories.  Sheesh.

KEIKO=`cd ../keiko; pwd`

set -x

./ppc $* >a.k \
    && "$KEIKO/pplink" -nostdlib -i "/usr/bin/env $KEIKO/ppx" \
        "$KEIKO/lib.k" a.k -o a.out >/dev/null \
    && chmod +x a.out
